stages:
- name: aaaaaaaaa
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:a-nginx-ldapauth-proxy
      version: 0.1.2
      name: nginx-ldapauth-proxy2
      targetNamespace: default
timeout: 60
notification: {}
